/**
 * The one pursuit every viewer test runs against.
 *
 * `fixtures/thursday.*` was generated by the real binary and is regenerated by
 * `./scripts/make-fixture.sh`. Tests read it rather than building graphs by hand, because a
 * hand-built graph is a graph the CLI never emitted — and the whole point of the viewer's
 * seam is that it renders exactly what the store produces.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { FoldResult, GraphProjection } from "@kona/core";
import { foldLog } from "@kona/core";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "..", "..", "..", "fixtures");

export const LOG_PATH = join(FIXTURES, "thursday.mutations.jsonl");
const GRAPH_PATH = join(FIXTURES, "thursday.graph.json");

export function logText(): string {
  return readFileSync(LOG_PATH, "utf8");
}

/** `kona graph --json` at head, as the binary wrote it — the read contract, on disk. */
export function graphJson(): GraphProjection & { torn_tail: boolean; damaged: unknown[] } {
  return JSON.parse(readFileSync(GRAPH_PATH, "utf8")) as GraphProjection & {
    torn_tail: boolean;
    damaged: unknown[];
  };
}

export function folded(upToVersion?: number): FoldResult {
  return foldLog(logText(), upToVersion === undefined ? {} : { upToVersion });
}

/** The head version of the fixture, read rather than hardcoded so a regen cannot strand it. */
export function headVersion(): number {
  return folded().graph.version;
}

/**
 * A wall clock fixed to a moment in the middle of the story, so countdown assertions are
 * stable. v7 was observed at 2026-08-22T00:53:59Z; `goalie-confirmed` is due at
 * 2026-08-21T17:00:00Z and `wait-for-eligibility-ruling` at 2026-08-21T12:00:00Z, so both are
 * already blown at head — which is exactly the state rule 8's third colour has to render.
 */
export const NOW = Date.parse("2026-08-22T01:00:00.000Z");
