/**
 * The one pursuit every viewer test runs against.
 *
 * `fixtures/thursday.*` was generated by the real binary and is regenerated by
 * `./scripts/make-fixture.sh`. Tests read it rather than building graphs by hand, because a
 * hand-built graph is a graph the CLI never emitted — and the whole point of the viewer's
 * seam is that it renders exactly what the store produces.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { FoldResult, GraphProjection } from "@kona/core";
import { foldLog } from "@kona/core";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "..", "..", "..", "fixtures");

export const LOG_PATH = join(FIXTURES, "thursday.mutations.jsonl");
const GRAPH_PATH = join(FIXTURES, "thursday.graph.json");

export function logText(): string {
  return readFileSync(LOG_PATH, "utf8");
}

/** `kona graph --json` at head, as the binary wrote it — the read contract, on disk. */
export function graphJson(): GraphProjection & { torn_tail: boolean; damaged: unknown[] } {
  return JSON.parse(readFileSync(GRAPH_PATH, "utf8")) as GraphProjection & {
    torn_tail: boolean;
    damaged: unknown[];
  };
}

export function folded(upToVersion?: number): FoldResult {
  return foldLog(logText(), upToVersion === undefined ? {} : { upToVersion });
}

/** The head version of the fixture, read rather than hardcoded so a regen cannot strand it. */
export function headVersion(): number {
  return folded().graph.version;
}

/**
 * The fixture's beats, by NAME rather than by number.
 *
 * Every version index in these tests used to be a literal, and regenerating the fixture then
 * meant editing about a hundred and fifty of them across seven files — which is both tedious
 * and the kind of edit that silently weakens a test when one gets it wrong. The story is
 * stable; only its numbering moves. So the numbering lives here, once.
 *
 * `beats.test.ts` pins every name below against the log itself, so a regen that reorders the
 * story fails in ONE place with a legible message rather than in thirty with arithmetic ones.
 *
 * Note how many versions the four sends take: two each — `effect reserve`, then `effect
 * record` — because §6.6 will not let a send be one commit. Priya's never gets its second
 * until v11, which is what leaves her node `sending` across four versions.
 */
export const V = {
  // Widened to `number` on purpose — no `as const`. Literal types here would make
  // `new Set([V.roster, V.plan])` a `Set<1 | 2>` and refuse every other version.
  /** `kona init`: identity and effect budget, no ops. */
  genesis: 0,
  /** The roster is read and recorded, before anyone on it is contacted (invariant 3(b)). */
  roster: 1,
  /** The approved plan: three goalies asked at once, merging on a predicate. */
  plan: 2,
  danaReserved: 3,
  danaSent: 4,
  samReserved: 5,
  samSent: 6,
  /** Reserved and then left open for four versions — crash window 2, on purpose. */
  priyaReserved: 7,
  danaDeclines: 8,
  /** Sam refuses and names Marcus, who is not on the roster. */
  samRefers: 9,
  /** The roster step is superseded by one that also checks eligibility. */
  rosterSuperseded: 10,
  /** The 550 comes back, and the outbox closes the slot it issued. */
  priyaFailed: 11,
  /** Priya's wait is dropped and Pat's arm is planned. */
  patPlanned: 12,
  /** Pat's slot is reserved and NOT closed. The fixture ends mid-flight, deliberately. */
  patReserved: 13,
};

/**
 * A wall clock fixed to a moment in the middle of the story, so countdown assertions are
 * stable. v7 was observed at 2026-08-22T00:53:59Z; `th-ymld` is due at
 * 2026-08-21T17:00:00Z and `th-9xi1` at 2026-08-21T12:00:00Z, so both are
 * already blown at head — which is exactly the state rule 8's third colour has to render.
 */
export const NOW = Date.parse("2026-08-22T01:00:00.000Z");

/**
 * The id the fixture minted for a node, found by its name.
 *
 * Ids are hashes, so a test cannot spell one from the person's name. The label is the stable
 * handle, and it is what the tests using this are actually asserting about.
 */
export function idOfName(name: string): string {
  for (const node of folded().graph.nodes.values()) {
    if (node.name === name) return node.id;
  }
  throw new Error(`the fixture has no node named "${name}"`);
}
